/* Begin generated Thrift model includes */
include "models/audit/Audit.thrift"
include "models/audit/AuditRecord.thrift"
include "models/commerce/Customer.thrift"
include "models/commerce/Employee.thrift"
include "models/commerce/Invoice.thrift"
include "models/commerce/InvoiceLine.thrift"
include "models/ddl/FlywaySchemaHistory.thrift"
include "models/media/Album.thrift"
include "models/media/Artist.thrift"
include "models/media/Genre.thrift"
include "models/media/MediaType.thrift"
include "models/media/Playlist.thrift"
include "models/media/PlaylistTrack.thrift"
include "models/media/Track.thrift"
include "models/note/Note.thrift"
include "models/sync/SyncProgress.thrift"
include "models/task/ScheduledTaskRun.thrift"
include "models/user/SystemUser.thrift"
/* End generated Thrift model includes */
