/* Begin generated Thrift service includes */
include "services/audit/AuditRecordService.thrift"
include "services/audit/AuditService.thrift"
include "services/commerce/CustomerService.thrift"
include "services/commerce/EmployeeService.thrift"
include "services/commerce/InvoiceLineService.thrift"
include "services/commerce/InvoiceService.thrift"
include "services/ddl/FlywaySchemaHistoryService.thrift"
include "services/media/AlbumService.thrift"
include "services/media/ArtistService.thrift"
include "services/media/GenreService.thrift"
include "services/media/MediaTypeService.thrift"
include "services/media/PlaylistService.thrift"
include "services/media/PlaylistTrackService.thrift"
include "services/media/TrackService.thrift"
include "services/note/NoteService.thrift"
include "services/sync/SyncProgressService.thrift"
include "services/task/ScheduledTaskRunService.thrift"
include "services/user/SystemUserService.thrift"
/* End generated Thrift service includes */
