apiVersion: v1
kind: Service
metadata:
  name: chinook
  labels:
    app: chinook
spec:
  ports:
  - port: 80
    targetPort: 9000
    name: http
  selector:
    app: chinook
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chinook
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: chinook
    spec:
      containers:
      - name: app
        image: chinook/chinook:latest
        ports:
        - containerPort: 9000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chinook-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: chinook.com
    http:
      paths:
      - backend:
          serviceName: chinook
          servicePort: 9000
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: chinook
  name: chinook-config
data:
  application.conf: |
    foo = "bar"
---
